version: "3.9"

services:
  mplink_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      DB_HOST: mplink_postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-marketplace_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      SERVER_PORT: ${SERVER_PORT:-8080}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mplink_postgres:
        condition: service_healthy
    networks:
      - mplink_net
      - marketplace_net

 
  mplink_postgres:
    image: postgis/postgis:16-3.5
    container_name: mplink_marketplace_db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5436}:5432"
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - mplink_pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mplink_net



volumes:
  mplink_pgdata:

networks:
  mplink_net:
    driver: bridge
  marketplace_net:
    external: true
